@echo off
REM =====================================================================================
REM Warehouse Management System - MySQL Automated Installation Configuration Script
REM Purpose: Automatically detect, configure and verify MySQL database
REM Usage: Double-click to run setup_mysql.bat
REM =====================================================================================

setlocal enabledelayedexpansion

echo.
echo ================================================================================
echo           Warehouse Management System - MySQL Auto Configuration Tool
echo ================================================================================
echo.

REM Set variables
set MYSQL_HOST=localhost
set MYSQL_PORT=3306
set DB_NAME=warehouse
set DB_USER=wms_user
set DB_PASSWORD=Wms@2024
set ROOT_PASSWORD=123456

REM Check if MySQL is installed
echo [1/5] Checking if MySQL is installed...
where mysql >nul 2>&1
if %errorlevel% neq 0 (
    echo [X] Error: MySQL command line tool not detected
    echo.
    echo Install MySQL first, MySQL 8.0 or higher is recommended
    echo Download: https://dev.mysql.com/downloads/mysql/
    echo.
    echo After installation, ensure:
    echo 1. MySQL service is started
    echo 2. MySQL bin directory is added to system PATH environment variable
    echo 3. Remember root user password
    echo.
    pause
    exit /b 1
)
echo [OK] MySQL command line tool detected successfully
echo.

REM Check if MySQL service is running
echo [2/5] Checking MySQL service status...
sc query MySQL80 >nul 2>&1
if %errorlevel% neq 0 (
    echo [!] Warning: MySQL80 service not detected
    echo Trying to detect other MySQL services...
    sc query MySQL >nul 2>&1
    if %errorlevel% neq 0 (
        echo [X] Error: MySQL service not running
        echo.
        echo Please start MySQL service:
        echo Method 1: Open "Services" manager, find MySQL service and start it
        echo Method 2: Run as administrator: net start MySQL80
        echo.
        pause
        exit /b 1
    ) else (
        echo [OK] MySQL service detected successfully
    )
) else (
    echo [OK] MySQL80 service detected successfully
)
echo.

REM Test MySQL connection
echo [3/5] Testing MySQL connection...
echo Please enter MySQL root user password (default is 123456):
set /p INPUT_ROOT_PASSWORD="Password (press Enter to use default):"
if "!INPUT_ROOT_PASSWORD!"=="" (
    set ROOT_PASSWORD=123456
) else (
    set ROOT_PASSWORD=!INPUT_ROOT_PASSWORD!
)

mysql -h%MYSQL_HOST% -P%MYSQL_PORT% -uroot -p%ROOT_PASSWORD% -e "SELECT 1" >nul 2>&1
if %errorlevel% neq 0 (
    echo [X] Error: Cannot connect to MySQL database
    echo.
    echo Please check:
    echo 1. Whether MySQL service is started
    echo 2. Whether root user password is correct
    echo 3. Whether MySQL port is 3306
    echo.
    pause
    exit /b 1
)
echo [OK] MySQL connection test successful
echo.

REM Execute database initialization script
echo [4/5] Initializing database...
echo Creating database and user...

set SCRIPT_DIR=%~dp0
set SQL_SCRIPT=%SCRIPT_DIR%init_database.sql

if not exist "%SQL_SCRIPT%" (
    echo [X] Error: Cannot find initialization script %SQL_SCRIPT%
    pause
    exit /b 1
)

mysql -h%MYSQL_HOST% -P%MYSQL_PORT% -uroot -p%ROOT_PASSWORD% < "%SQL_SCRIPT%"
if %errorlevel% neq 0 (
    echo [X] Error: Database initialization failed
    pause
    exit /b 1
)
echo [OK] Database initialization successful
echo.

REM Verify database connection
echo [5/5] Verifying database configuration...
mysql -h%MYSQL_HOST% -P%MYSQL_PORT% -u%DB_USER% -p%DB_PASSWORD% -e "USE %DB_NAME%; SELECT 'Database connection successful!' AS Status;"
if %errorlevel% neq 0 (
    echo [X] Error: Database user connection failed
    pause
    exit /b 1
)
echo [OK] Database configuration verification successful
echo.

REM Generate configuration file
echo Generating configuration file...
set CONFIG_FILE=%SCRIPT_DIR%..\src\main\resources\application-dev.properties

(
echo # =====================================================================================
echo # Warehouse Management System - Development Environment Configuration File
echo # This file is automatically generated by setup_mysql.bat
echo # =====================================================================================
echo.
echo # Database configuration
echo spring.datasource.url=jdbc:mysql://%MYSQL_HOST%:%MYSQL_PORT%/%DB_NAME%?useUnicode=true^&characterEncoding=UTF-8^&serverTimezone=Asia/Shanghai^&allowPublicKeyRetrieval=true^&useSSL=false
echo spring.datasource.username=%DB_USER%
echo spring.datasource.password=%DB_PASSWORD%
) > "%CONFIG_FILE%"

echo [OK] Configuration file generated: %CONFIG_FILE%
echo.

REM Display configuration summary
echo ================================================================================
echo                              Configuration Complete!
echo ================================================================================
echo.
echo Database Information:
echo   - Host: %MYSQL_HOST%
echo   - Port: %MYSQL_PORT%
echo   - Database Name: %DB_NAME%
echo   - Username: %DB_USER%
echo   - Password: %DB_PASSWORD%
echo.
echo Configuration File:
echo   - %CONFIG_FILE%
echo.
echo Next Steps:
echo   1. Start backend service: mvn spring-boot:run
echo   2. Access API documentation: http://localhost:8080/api/swagger-ui.html
echo   3. Start frontend service: cd frontend ^&^& npm run dev
echo   4. Note: Port configuration is unified in application.properties
echo.
echo ================================================================================
echo.

pause
