export const HTTP_STATUS_CODES = {
  OK: 200,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  METHOD_NOT_ALLOWED: 405,
  CONFLICT: 409,
  UNSUPPORTED_MEDIA_TYPE: 415,
  UNPROCESSABLE_ENTITY: 422,
  INTERNAL_SERVER_ERROR: 500,
  BAD_GATEWAY: 502,
  SERVICE_UNAVAILABLE: 503,
  GATEWAY_TIMEOUT: 504,
};

export const HTTP_STATUS_MESSAGES = {
  [HTTP_STATUS_CODES.OK]: '操作成功',
  [HTTP_STATUS_CODES.BAD_REQUEST]: '请求参数错误',
  [HTTP_STATUS_CODES.UNAUTHORIZED]: '未授权，请重新登录',
  [HTTP_STATUS_CODES.FORBIDDEN]: '拒绝访问',
  [HTTP_STATUS_CODES.NOT_FOUND]: '请求资源不存在',
  [HTTP_STATUS_CODES.METHOD_NOT_ALLOWED]: '请求方法不允许',
  [HTTP_STATUS_CODES.CONFLICT]: '资源冲突，请刷新后重试',
  [HTTP_STATUS_CODES.UNSUPPORTED_MEDIA_TYPE]: '不支持的媒体类型',
  [HTTP_STATUS_CODES.UNPROCESSABLE_ENTITY]: '数据验证错误',
  [HTTP_STATUS_CODES.INTERNAL_SERVER_ERROR]: '服务器内部错误',
  [HTTP_STATUS_CODES.BAD_GATEWAY]: '网关错误',
  [HTTP_STATUS_CODES.SERVICE_UNAVAILABLE]: '服务暂不可用',
  [HTTP_STATUS_CODES.GATEWAY_TIMEOUT]: '网关超时',
};

export const BUSINESS_ERROR_CODES = {
  SUCCESS: 200,
  SYSTEM_ERROR: 1001001,
  SERVICE_UNAVAILABLE: 1001002,
  PARAM_ERROR: 1001003,
  METHOD_NOT_ALLOWED: 1001004,
  RESOURCE_NOT_FOUND: 1001005,
  REQUEST_TOO_FREQUENT: 1001006,
  OPERATION_TIMEOUT: 1001007,
  DATA_VERSION_CONFLICT: 1001008,
  DATABASE_ERROR: 1001009,

  UNAUTHORIZED: 1101001,
  ACCESS_DENIED: 1101002,
  TOKEN_INVALID: 1101003,
  TOKEN_EXPIRED: 1101004,
  LOGIN_FAILED: 1101005,
  ACCOUNT_DISABLED: 1101006,
  ACCOUNT_LOCKED: 1101007,
  PASSWORD_ERROR_TOO_MANY: 1101008,
  CAPTCHA_ERROR: 1101009,
  TWO_FACTOR_REQUIRED: 1101010,

  DEVICE_NOT_FOUND: 2001001,
  DEVICE_CODE_EXISTS: 2001002,
  DEVICE_STATUS_NOT_ALLOWED: 2001003,
  DEVICE_ALREADY_BORROWED: 2001004,
  DEVICE_UNDER_MAINTENANCE: 2001005,
  DEVICE_SCRAPPED: 2001006,
  DEVICE_TYPE_NOT_FOUND: 2002001,
  DEVICE_TYPE_CODE_EXISTS: 2002002,
  DEVICE_TYPE_IN_USE: 2002003,
  DEVICE_STATUS_TRANSITION_INVALID: 2003001,
  DEVICE_STATUS_NEED_APPROVAL: 2003002,

  INSUFFICIENT_STOCK: 2101001,
  INVENTORY_NOT_FOUND: 2101002,
  INVENTORY_LOCKED: 2101003,
  INVENTORY_OPERATION_FAILED: 2101004,
  INVENTORY_DATA_INCONSISTENT: 2101005,
  BIN_NOT_FOUND: 2102001,
  BIN_FULL: 2102002,
  BIN_OCCUPIED: 2102003,
  AREA_NOT_FOUND: 2103001,
  AREA_CODE_EXISTS: 2103002,

  ORDER_NOT_FOUND: 2201001,
  ORDER_STATUS_NOT_ALLOWED: 2201002,
  ORDER_NO_EXISTS: 2201003,
  ORDER_ITEMS_EMPTY: 2201004,
  ORDER_ALREADY_SUBMITTED: 2201005,
  ORDER_ALREADY_APPROVED: 2201006,
  ORDER_ALREADY_CANCELLED: 2201007,
  ORDER_ALREADY_COMPLETED: 2201008,
  OUTBOUND_FAILED: 2202001,
  INBOUND_FAILED: 2202002,
  TRANSFER_FAILED: 2202003,

  USER_NOT_FOUND: 2301001,
  USERNAME_EXISTS: 2301002,
  EMAIL_EXISTS: 2301003,
  PHONE_EXISTS: 2301004,
  INVALID_PASSWORD: 2301005,
  OLD_PASSWORD_ERROR: 2301006,
  USER_STATUS_INVALID: 2301007,

  ROLE_NOT_FOUND: 2401001,
  ROLE_NAME_EXISTS: 2401002,
  ROLE_CODE_EXISTS: 2401003,
  ROLE_IN_USE: 2401004,
  PERMISSION_DENIED: 2401005,

  FILE_NOT_FOUND: 4001001,
  FILE_UPLOAD_FAILED: 4001002,
  FILE_DOWNLOAD_FAILED: 4001003,
  FILE_DELETE_FAILED: 4001004,
  FILE_SIZE_EXCEEDED: 4001005,
  FILE_TYPE_NOT_ALLOWED: 4001006,
  FILE_NAME_INVALID: 4001007,

  EXTERNAL_API_ERROR: 5001001,
  EXTERNAL_API_TIMEOUT: 5001002,
  EXTERNAL_API_UNAVAILABLE: 5001003,
};

export const BUSINESS_ERROR_MESSAGES = {
  [BUSINESS_ERROR_CODES.SYSTEM_ERROR]: '系统内部错误，请联系管理员',
  [BUSINESS_ERROR_CODES.SERVICE_UNAVAILABLE]: '服务暂不可用，请稍后重试',
  [BUSINESS_ERROR_CODES.PARAM_ERROR]: '请求参数错误',
  [BUSINESS_ERROR_CODES.METHOD_NOT_ALLOWED]: '请求方式不支持',
  [BUSINESS_ERROR_CODES.RESOURCE_NOT_FOUND]: '请求的资源不存在',
  [BUSINESS_ERROR_CODES.REQUEST_TOO_FREQUENT]: '请求过于频繁，请稍后再试',
  [BUSINESS_ERROR_CODES.OPERATION_TIMEOUT]: '操作超时，请重试',
  [BUSINESS_ERROR_CODES.DATA_VERSION_CONFLICT]: '数据已被修改，请刷新后重试',
  [BUSINESS_ERROR_CODES.DATABASE_ERROR]: '数据库操作失败',

  [BUSINESS_ERROR_CODES.UNAUTHORIZED]: '未登录或登录已过期，请重新登录',
  [BUSINESS_ERROR_CODES.ACCESS_DENIED]: '访问被拒绝，权限不足',
  [BUSINESS_ERROR_CODES.TOKEN_INVALID]: '登录凭证无效，请重新登录',
  [BUSINESS_ERROR_CODES.TOKEN_EXPIRED]: '登录已过期，请重新登录',
  [BUSINESS_ERROR_CODES.LOGIN_FAILED]: '用户名或密码错误',
  [BUSINESS_ERROR_CODES.ACCOUNT_DISABLED]: '账号已被禁用，请联系管理员',
  [BUSINESS_ERROR_CODES.ACCOUNT_LOCKED]: '账号已被锁定，请30分钟后重试',
  [BUSINESS_ERROR_CODES.PASSWORD_ERROR_TOO_MANY]: '密码错误次数过多，请30分钟后重试',
  [BUSINESS_ERROR_CODES.CAPTCHA_ERROR]: '验证码错误或已过期',
  [BUSINESS_ERROR_CODES.TWO_FACTOR_REQUIRED]: '需要进行二次认证',

  [BUSINESS_ERROR_CODES.DEVICE_NOT_FOUND]: '设备不存在',
  [BUSINESS_ERROR_CODES.DEVICE_CODE_EXISTS]: '设备编码已存在',
  [BUSINESS_ERROR_CODES.DEVICE_STATUS_NOT_ALLOWED]: '当前设备状态不允许此操作',
  [BUSINESS_ERROR_CODES.DEVICE_ALREADY_BORROWED]: '设备已被借用',
  [BUSINESS_ERROR_CODES.DEVICE_UNDER_MAINTENANCE]: '设备维修中，暂不可用',
  [BUSINESS_ERROR_CODES.DEVICE_SCRAPPED]: '设备已报废',
  [BUSINESS_ERROR_CODES.DEVICE_TYPE_NOT_FOUND]: '设备类型不存在',
  [BUSINESS_ERROR_CODES.DEVICE_TYPE_CODE_EXISTS]: '设备类型编码已存在',
  [BUSINESS_ERROR_CODES.DEVICE_TYPE_IN_USE]: '设备类型已被使用，无法删除',
  [BUSINESS_ERROR_CODES.DEVICE_STATUS_TRANSITION_INVALID]: '设备状态流转非法',
  [BUSINESS_ERROR_CODES.DEVICE_STATUS_NEED_APPROVAL]: '设备状态变更需要审批',

  [BUSINESS_ERROR_CODES.INSUFFICIENT_STOCK]: '库存不足',
  [BUSINESS_ERROR_CODES.INVENTORY_NOT_FOUND]: '库存记录不存在',
  [BUSINESS_ERROR_CODES.INVENTORY_LOCKED]: '库存已被锁定',
  [BUSINESS_ERROR_CODES.INVENTORY_OPERATION_FAILED]: '库存操作失败',
  [BUSINESS_ERROR_CODES.INVENTORY_DATA_INCONSISTENT]: '库存数据不一致',
  [BUSINESS_ERROR_CODES.BIN_NOT_FOUND]: '货位不存在',
  [BUSINESS_ERROR_CODES.BIN_FULL]: '货位已满',
  [BUSINESS_ERROR_CODES.BIN_OCCUPIED]: '货位已被占用',
  [BUSINESS_ERROR_CODES.AREA_NOT_FOUND]: '库区不存在',
  [BUSINESS_ERROR_CODES.AREA_CODE_EXISTS]: '库区编码已存在',

  [BUSINESS_ERROR_CODES.ORDER_NOT_FOUND]: '订单不存在',
  [BUSINESS_ERROR_CODES.ORDER_STATUS_NOT_ALLOWED]: '当前订单状态不允许此操作',
  [BUSINESS_ERROR_CODES.ORDER_NO_EXISTS]: '订单号已存在',
  [BUSINESS_ERROR_CODES.ORDER_ITEMS_EMPTY]: '订单明细不能为空',
  [BUSINESS_ERROR_CODES.ORDER_ALREADY_SUBMITTED]: '订单已提交，请勿重复提交',
  [BUSINESS_ERROR_CODES.ORDER_ALREADY_APPROVED]: '订单已审核',
  [BUSINESS_ERROR_CODES.ORDER_ALREADY_CANCELLED]: '订单已取消',
  [BUSINESS_ERROR_CODES.ORDER_ALREADY_COMPLETED]: '订单已完成',
  [BUSINESS_ERROR_CODES.OUTBOUND_FAILED]: '出库单执行失败',
  [BUSINESS_ERROR_CODES.INBOUND_FAILED]: '入库单执行失败',
  [BUSINESS_ERROR_CODES.TRANSFER_FAILED]: '调拨单执行失败',

  [BUSINESS_ERROR_CODES.USER_NOT_FOUND]: '用户不存在',
  [BUSINESS_ERROR_CODES.USERNAME_EXISTS]: '用户名已存在',
  [BUSINESS_ERROR_CODES.EMAIL_EXISTS]: '邮箱已存在',
  [BUSINESS_ERROR_CODES.PHONE_EXISTS]: '手机号已存在',
  [BUSINESS_ERROR_CODES.INVALID_PASSWORD]: '密码格式不正确',
  [BUSINESS_ERROR_CODES.OLD_PASSWORD_ERROR]: '原密码错误',
  [BUSINESS_ERROR_CODES.USER_STATUS_INVALID]: '用户状态无效',

  [BUSINESS_ERROR_CODES.ROLE_NOT_FOUND]: '角色不存在',
  [BUSINESS_ERROR_CODES.ROLE_NAME_EXISTS]: '角色名称已存在',
  [BUSINESS_ERROR_CODES.ROLE_CODE_EXISTS]: '角色编码已存在',
  [BUSINESS_ERROR_CODES.ROLE_IN_USE]: '角色已被使用，无法删除',
  [BUSINESS_ERROR_CODES.PERMISSION_DENIED]: '权限不足',

  [BUSINESS_ERROR_CODES.FILE_NOT_FOUND]: '文件不存在',
  [BUSINESS_ERROR_CODES.FILE_UPLOAD_FAILED]: '文件上传失败',
  [BUSINESS_ERROR_CODES.FILE_DOWNLOAD_FAILED]: '文件下载失败',
  [BUSINESS_ERROR_CODES.FILE_DELETE_FAILED]: '文件删除失败',
  [BUSINESS_ERROR_CODES.FILE_SIZE_EXCEEDED]: '文件大小超出限制',
  [BUSINESS_ERROR_CODES.FILE_TYPE_NOT_ALLOWED]: '不支持的文件类型',
  [BUSINESS_ERROR_CODES.FILE_NAME_INVALID]: '文件名无效',

  [BUSINESS_ERROR_CODES.EXTERNAL_API_ERROR]: '外部接口调用失败',
  [BUSINESS_ERROR_CODES.EXTERNAL_API_TIMEOUT]: '外部接口调用超时',
  [BUSINESS_ERROR_CODES.EXTERNAL_API_UNAVAILABLE]: '外部接口暂不可用',
};

export const ERROR_CODES = {
  NETWORK_ERROR: 'NETWORK_ERROR',
  TIMEOUT_ERROR: 'TIMEOUT_ERROR',
  AUTH_ERROR: 'AUTH_ERROR',
  PERMISSION_DENIED: 'PERMISSION_DENIED',
  NOT_FOUND: 'NOT_FOUND',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  SERVER_ERROR: 'SERVER_ERROR',
  UNKNOWN_ERROR: 'UNKNOWN_ERROR',
};

export const ERROR_MESSAGES = {
  [ERROR_CODES.NETWORK_ERROR]: {
    title: '网络连接失败',
    message: '无法连接到服务器，请检查您的网络连接',
    action: '重试',
  },
  [ERROR_CODES.TIMEOUT_ERROR]: {
    title: '请求超时',
    message: '服务器响应超时，请稍后重试',
    action: '重试',
  },
  [ERROR_CODES.AUTH_ERROR]: {
    title: '认证失败',
    message: '您的登录已过期，请重新登录',
    action: '重新登录',
  },
  [ERROR_CODES.PERMISSION_DENIED]: {
    title: '权限不足',
    message: '您没有权限执行此操作',
    action: '联系管理员',
  },
  [ERROR_CODES.NOT_FOUND]: {
    title: '资源不存在',
    message: '请求的资源不存在或已被删除',
    action: '返回首页',
  },
  [ERROR_CODES.VALIDATION_ERROR]: {
    title: '数据验证失败',
    message: '提交的数据格式不正确，请检查后重试',
    action: '检查数据',
  },
  [ERROR_CODES.SERVER_ERROR]: {
    title: '服务器错误',
    message: '服务器发生错误，请稍后重试',
    action: '重试',
  },
  [ERROR_CODES.UNKNOWN_ERROR]: {
    title: '未知错误',
    message: '发生未知错误，请稍后重试',
    action: '重试',
  },
};

export function getErrorMessage(errorCode, defaultMessage = '操作失败') {
  return BUSINESS_ERROR_MESSAGES[errorCode] || defaultMessage;
}

export function getHttpErrorMessage(statusCode) {
  return HTTP_STATUS_MESSAGES[statusCode] || '请求失败';
}

export function isBusinessError(errorCode) {
  return errorCode >= 1000 && errorCode <= 999999;
}

export function isSystemError(errorCode) {
  return errorCode >= 1001000 && errorCode < 1100000;
}

export function isAuthError(errorCode) {
  return errorCode >= 1101000 && errorCode < 1200000;
}

export function isNetworkError(error) {
  return error && !error.response && error.request;
}

export function isTimeoutError(error) {
  return error && error.code === 'ECONNABORTED';
}

export function isPermissionError(error) {
  return error && error.response?.status === 403;
}

export default {
  HTTP_STATUS_CODES,
  HTTP_STATUS_MESSAGES,
  BUSINESS_ERROR_CODES,
  BUSINESS_ERROR_MESSAGES,
  ERROR_CODES,
  ERROR_MESSAGES,
  getErrorMessage,
  getHttpErrorMessage,
  isBusinessError,
  isSystemError,
  isAuthError,
  isNetworkError,
  isTimeoutError,
  isPermissionError,
};
